config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :reviews, only: [:index, :new, :create, :destroy]

  resources :routes, only: [:show, :index] do
    # agrego las rutas de favorites dentro de routes
    resources :favorites, only: [:show, :create]
  end
  resources :favorites, only: [:destroy, :index]
  resources :stop_stations, only: :index
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :route
  validates :user, uniqueness: {scope: :route}
  scope :user_faborites, ->(user) { where("user_id=?", user.id) }
  scope :route_faborites, ->(route) { where("route_id=?", route.id) }

  include PgSearch::Model
  pg_search_scope :search_by_mark_favourite,
    against: [ :user_id, :route_id ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :route
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/near_place.rb
class NearPlace < ApplicationRecord
  belongs_to :place
  belongs_to :stop_station
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :near_places
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :stop_stations
  has_many :favorites
  has_many :reviews, dependent: :destroy
  has_many :spots, dependent: :destroy
  has_many :hours, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_routes,
    against: [ :name, :code ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :route
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_spots,
    against: [ :route_id ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/stop_station.rb
class StopStation < ApplicationRecord
  has_many :stop_times
  has_many :near_places
  belongs_to :route
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  scope :route_stations, ->(route) { where("route_id=?", route.id) }

  include PgSearch::Model
  pg_search_scope :search_by_routes,
    against: [ :station_name, :address, :route_id ],
    associated_against: {
      route: [ :name, :code ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/stop_time.rb
class StopTime < ApplicationRecord
  belongs_to :stop_station
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:destroy, :show]
  before_action :set_user, only: [:index, :create]
  before_action :set_route, only: [:indedx, :create]
  before_action :set_array_routes, only: [:index, :show ]
  def index
    @favorites = Favorite.all
    sugestions(@array_routes)
  end

  def show
    @favorite = Favorite.find(params[:id])
    sugestions(@array_routes)
  end

  def create
    @favorite = Favorite.new
    @favorite.mark_favourite = true
    @favorite.route = @route
    @favorite.user = current_user
    if @favorite.save!
      redirect_to favorites_path
    else
      render 'routes/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorites_path
  end

  private

  def favorite_params
    params.require(:favorite).permit(:route_id, :user_id)
  end

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def set_route
    @route = Route.find(params[:route_id])
  end

  def set_array_routes
    @array_routes = Route.all
  end

  def sugestions(array_routes)
    @sugestions = array_routes.map do |route|
      route.name
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  before_action :set_array_routes, only: [:home]
  def home
    @locations = Location.all
    marks(@locations)
    sugestions(@array_routes)
  end

  private

  def set_array_routes
    @array_routes = Route.all
  end

  def marks(locations)
    @markers = locations.geocoded.map do |location|
      {
        latitude: location.latitude,
        longitude: location.longitude
      }
    end
  end

  def sugestions(array_routes)
    @sugestions = array_routes.map do |route|
      route.name
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_route, only: [:show]
  before_action :set_stop_station, only: [:show]
  before_action :set_array_routes, only: [:index, :show]
  before_action :set_spots, only: [:show]
  before_action :set_array_routes, only: [:show, :index]


  def index

    if params[:query].present?
      @routes = Route.search_by_routes(params[:query])
    else
      @routes = []
    end
    @locations = Location.all
    not_marks(@locations)
    sugestions(@array_routes)
  end

  def show
    marks(@stop_stations)
    line_spots(@spots)
    sugestions(@array_routes)
    if user_signed_in?
      @mark_favourite = Favorite.where(user_id: current_user.id, route_id: @route.id)
    else
      @mark_favourite = []
      @mark_favourite << Favorite.new
    end
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def set_stop_station
    @stop_stations = StopStation.search_by_routes(@route.id)
  end

  def set_spots
    @spots = Spot.search_by_spots(@route.id)
  end

  def set_array_routes
    @array_routes = Route.all
  end

  def not_marks(locations)
    @markers = locations.geocoded.map do |location|
      {
        latitude: location.latitude,
        longitude: location.longitude
      }
    end
  end

  def marks(locations)
    @markers = locations.geocoded.map do |location|
      {
        latitude: location.latitude,
        longitude: location.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { location: location })
      }
    end
  end

  def line_spots(spots)
    @lines = spots.geocoded.map do |spot|
      [spot.longitude, spot.latitude]
    end
  end

  def sugestions(array_routes)
    @sugestions = array_routes.map do |route|
      route.name
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_array_routes, only: [:show]

  def show
    @user = User.find(params[:id])
    sugestions(@array_routes)
  end

  def set_array_routes
    @array_routes = Route.all
  end

  def sugestions(array_routes)
    @sugestions = array_routes.map do |route|
      route.name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/index.html.erb
<div class="border min-vh-100" style="background-image: url(https://res.cloudinary.com/dqij49pio/image/upload/v1667677528/IMG_8692_ripdqq.jpg); background-size: cover; background-position: center; background-repeat: no-repeat">
    <div class="d-flex justify-content-between border-bottom border-2 border-opacity-75 border-secondary bg-white p-2">
      <p class= "btn buttons shadow-sm rounded-5 mt-2"> <%= link_to "Home", root_path, class:"text-decoration-none text-black pt-2"  %></p>
      <h2 class="pt-2 fw-bold">FAVORITOS</h2>
      <i class="fa-solid fa-signs-post fs-1 pt-2"></i>
    </div>
  <div class="container p-2">

      <div class="row p-1 mx-auto">
      <% @favorites.each do |favorite| %>

        <div class="col-12 col-md-6 col-lg-4 m-1 mx-auto">

          <div class="card rounded rounded-4 p-4" style="background-image: url(<%= favorite.route.image %>); background-size: cover; background-position: center; background-repeat: no-repeat">

            <div class="card-body rounded rounded-4" style="background-image: linear-gradient(rgb(236, 240, 241), rgba(236, 240, 241, 0.7))">
                  <% route = favorite.route %>
              <div class="d-flex justify-content-between ">
                <p class = "fs-3"> <%= route.name %> </p>
                <i class="fa-solid fa-heart pt-2 text-danger"></i>
              </div>
              <p class = "fs-4 fw-bold"> <%= "$#{route.price}" %>
              <p> <i class="fa-solid fa-bus-simple"></i> <%= route.code %> <br>
              <i class="fa-regular fa-clock"></i> <%= " horario: #{route.start_hour} - #{route.end_hour}"%>
              <br>


                <%# hour = Time.now.hour %>
                <%# min = Time.now.min %>
                <%# if 30 < min %>
                  <%# hour += 1 %>
                  <%# first = "#{hour}:00" %>
                  <%# second = "#{hour}:30" %>
                <%# else %>
                  <%# first = "#{hour}:30"  %>
                  <%# second = "#{hour + 1}:00" %>
                <%# end %>

               <%# <i class="fa-solid fa-person-shelter"></i>  %> <%#= "El siguiente bus estara aquí a las: #{first}, #{second} " %>

              <div class="d-flex justify-content-between">
                <%= link_to favorite_path(favorite), method: :delete, data: { turbo_method: :delete, turbo_confirm: '¿Quieres quitar esta ruta de tus favoritos?' } do  %>
                  <i class="fa-regular fa-trash-can text-black fs-4"></i>
                <% end %>
                <%= link_to "📍 Ver ruta", route_path(favorite.route_id), class:"btn buttons rounded-5 shadow" %>
              </div>
            </div>

          </div>

        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VieneElBus</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <header>
      <%= render "shared/navbar" %>
    </header>

    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="backg">
  <div class="container text-center">
    <div class="row">
      <div class="col-md-7 col-sm-12">
        <div class="container" style="height: 50px"></div>
        <h1><strong>VIENE EL BUS</strong> <i class="fa-solid fa-bus"></i></h1>
        <p><strong>Viene el bus</strong> en cualquier lugar, en cualquier momento.
        </p>
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="https://res.cloudinary.com/dqij49pio/image/upload/v1668065582/pexels-ingo-joseph-35969_suxefn.jpg" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h5><strong>Monitorea</strong> en tiempo real tus rutas <i class="fa-solid fa-location-dot"></i></h5>
                <p>Así podrás organizar mejor tu agenda</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="https://res.cloudinary.com/dqij49pio/image/upload/v1668065906/pexels-roussety-gregory-4055666_dvxlfz.jpg" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h5><strong>Guarda</strong> tus rutas favoritas <i class="fa-solid fa-heart"></i></h5>
                <p>Así las podras llevar donde quiera que vayas.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="https://res.cloudinary.com/dqij49pio/image/upload/v1668065135/pexels-alexander-isreb-1784142_eeczli.jpg" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h5><strong>Organiza</strong> mejor tu tiempo</h5>
                <p>Con <strong>Viene el bus</strong> la incertidumbre no hará parte de tus viajes.</p>
              </div>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
      <div class="col-md-5 col-sm-12">
                <div class="container" id="holdf">

                <div class="container flex-row bd-highlight mb-3">
                  <p>
                    <a class="btn btn-outline-warning" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1"><i class="fa-solid fa-magnifying-glass-location"></i> <strong>Busca tu ruta</strong></a>
                  </p>
                  <div class="row">
                    <div style="min-height: 120px;">
                      <div class="collapse collapse-horizontal" id="multiCollapseExample1">
                        <div class="card card-body" style="width: 500px;">
                          En cuanto estes listo, no dudes en utilizar nuestra barra de busqueda para encontrar la ruta que necesitas, será un placer para nosotros acompañarte en este viaje.
                        </div>
                      </div>
                    </div>
                </div>


                <div class="container flex-row-reverse bd-highlight" id="holdf2">
                  <p>
                    <button class="btn btn-outline-warning" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2"><i class="fa-solid fa-heart-circle-plus"></i> <strong>Rutas favoritas</strong></button>
                  </p>
                    <div style="min-height: 120px;">
                      <div class="collapse collapse-horizontal" id="multiCollapseExample2">
                        <div class="card card-body" style="width: 500px;">
                          Para poder guardar tus rutas favoritas tendrás que registrarte pero te aseguramos que valdrá la pena, podrás acceder a tus rutas favoritas de manera rapida y sencilla.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

      </div>
    </div>

    <div class="container text-center border-bottom border-warning" style="height: 100px" id="holdf3">
      <h1><i class="fa-sharp fa-solid fa-map-location-dot fa-2xl"></i></h1>
    </div>
    <div class="d-flex justify-content-between">
      <img src="https://res.cloudinary.com/dqij49pio/image/upload/v1667963433/lw_logo_square-300x300_jsxwwj_xjypjd.png" alt="">
      <img src="https://res.cloudinary.com/dqij49pio/image/upload/v1667920641/forte_eidquk.png" alt="" class="logof">
    </div>
  </div>
</div>

app/views/routes/index.html.erb
<div>

  <div data-controller = "lateral-menu" class="lateral__menu d-flex">
    <div class="menu__side"
      data-lateral-menu-target = "menu"
      id="menu_side">
      <div id = 'list-routes'>
        <div class="card p-4">
          <p class= "h3">
            <% if params[:query].blank? %>
              <%= pluralize @routes.count, "Resultados" %> obtenidos
            <% else %>
                <%= pluralize @routes.count , "Resultados" %> de <code><%= params[:query] %></code>
            <% end %>
          </p>
        </div>
        <div class="">
          <div class="">
            <% @routes.each do |route| %>
              <div class="">
                  <%= link_to route_path(route), class:"car-link" do%>
                    <%= render "shared/cards_route", route:route  %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
    <div class = "icon__menu" data-lateral-menu-target ="close"
    id = "close"
    data-action = "click->lateral-menu#openCloseMenu">
      <i class="fa-solid fa-caret-left "></i>
    </div>

  </div>
  <div class="">
    <%= render "shared/map"%>
  </div>
</div>

app/views/routes/show.html.erb
<div>
  <div data-controller = "lateral-menu" class="lateral__menu d-flex">
    <div class="menu__side"
      data-lateral-menu-target = "menu"
      id="menu_side">


      <div class="card">
        <div class= "d-flex card-header align-items-center p-3 ">
          <h4 class= "col-11 m-0"><strong><%= @route.name %></strong></h4>
          <div class= "icon__favorites col-1 text-align-center">
            <% if user_signed_in? %>
              <% if @mark_favourite.present?%>
                <i class="fa-solid fa-heart"></i>
              <% else %>
                <%= link_to route_favorites_path(@route), data: {turbo_method: :post}, class: "icon__favorites" do%>
                  <i class="fa-regular fa-heart"></i>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "icon__favorites" do%>
                <i class="fa-regular fa-heart"></i>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="card-header">
          <h5 class="card-title"><strong><%= @route.price %></strong></h5>
          <p class="m-0"><%= @route.code %></p>
          <p class="m-0"><%= @stop_stations.length%> Estaciones</p>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <% @stop_stations.each do |stop_station|%>
          <div class="list-group-item  ">
            <h5 class="card-title mt-3"><%= stop_station.station_name %></h5>
            <h6 class="card-subtitle text-muted mb-3"><%= stop_station.address %></h6>
            <% hour = Time.now.hour %>
            <% min = Time.now.min %>
            <% plus_min_array = [3, 4, 5] %>
            <% plus_min = plus_min_array.sample %>
            <% sum = min + plus_min %>
            <% if 60 <= sum %>
              <% hour += 1 %>
              <% first = "#{hour}:0#{sum-60}" %>
            <% else %>
              <% first = "#{hour}:#{sum}"  %>
            <% end %>

            <h6> <i class="fa-solid fa-person-shelter"></i> <%= "El siguiente bus estara aquí a las: #{first}" %> </h6>
          </div>
        <% end %>
      </ul>

        <div>
          <h4></h4>
          <h4></h4>
        </div>

    </div>
    <div class = "icon__menu" data-lateral-menu-target ="close"
    id = "close"
    data-action = "click->lateral-menu#openCloseMenu">
      <i class="fa-solid fa-caret-left "></i>
    </div>

  </div>
  <div class="">
    <%= render "shared/map_query" %>
  </div>
</div>

app/views/shared/_cards_route.html.erb
<div class="card box" style="background-image: url(<%= route.image %>)">
  <div class="card-body box-car">
    <h4 class="text-break card-title"><%= route.name %></h4>
      <p><%= route.price %></p>
      <p><%= route.code %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<% if location.instance_of? Location %>
  <h5> <%= location.name %></h5>
  <p><%= location.address %></p>
<% else %>
  <h5> <%= location.station_name %></h5>
  <p><%= location.address %></p>
<% end %>

app/views/shared/_map.html.erb
<div id='map' class = "map"
data-controller="map-home"
data-map-home-api-key-value="<%=ENV['MAPBOX_API_KEY']%>"
data-map-home-markers-value="<%= @markers.to_json %>"
></div>

app/views/shared/_map_query.html.erb
<div id='map' class = "map"
data-controller="map"
data-map-api-key-value="<%=ENV['MAPBOX_API_KEY']%>"
data-map-markers-value="<%= @markers.to_json %>"
data-map-lines-value="<%= @lines %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar">
  <div class="container-fluid">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dqij49pio/image/upload/v1667695896/Viene%20el%20bus/icono_kblhdb_xcghxv.png" %>
    <% end %>

    <div data-controller = "suggestions-search"
    data-suggestions-search-suggestions-value = "<%= @sugestions %>"
    >
      <%= form_with url: routes_path, method: :get, html: {class: "search_bar mb-4", data: { search_route_target: "form" }, autocomplete: "off"} do %>
        <%= text_field_tag :query,
                            params[:query],
                            class: "bar",
                            placeholder: "¿Dónde quieres viajar hoy?",
                            data: {suggestions_search_target: "input"}
                            %>
        <%= image_submit_tag "https://res.cloudinary.com/dqij49pio/image/upload/v1666413182/Viene%20el%20bus/mdi_search_igzh6c.png", class: "serch "%>
      <% end %>

      <div data-suggestions-search-target = "content"
      class = "search-input-box">
        <ul data-suggestions-search-target = "results"
        class = "container-suggestions">
        </ul>
      </div>
    </div>




    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%= link_to root_path do %>
            <li class="nav-item active">
              <%= image_tag "https://res.cloudinary.com/dqij49pio/image/upload/v1667688487/Viene%20el%20bus/Home_jum3xt.png", class: "avatar icons-small dropdown-toggle"%>
            </li>
          <% end %>

          <li class="nav-item">
            <%= image_tag "https://res.cloudinary.com/dqij49pio/image/upload/v1667688487/Viene%20el%20bus/Camapa_de_notificaciones_wompaf.png", class: "avatar icons-small dropdown-toggle" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dqij49pio/image/upload/v1667688487/Viene%20el%20bus/Account_eoaxbm.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mi perfil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Mis rutas", favorites_path , class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Crear cuenta", new_user_registration_path, class: "navbar-btn-yellow"%>
          </li>
            <%= link_to "Iniciar sesión", new_user_session_path, class: "navbar-btn-yellow br"%>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class= "d-flex justify-content-center login min-vh-100 border-0 rounded">
  <div class="card d-flex justify-content-center mt-5 p-2 align-self-start border-0 rounded-3" style= "width: 50%" >
    <div class="card-header text-center border-0 rounded-3 fondo">
      <h1 class= "fw-bold border-0 fondo"> ¡Todo listo para tu recorrido! </h1>
    </div >
     <div class="perfilusuario border-0 rounded-3 bg-transparent">
     <div class= "border-0">
      <p class="fw-bold fs-2 d-flex justify-content-center">Hey You! <%= @user.email %></p>
    </div>
  </div>
  <div>
    <div class= "d-flex justify-content-between align-self-start border-0 rounded">
      <div>
       <p class="btn buttons justify-content-center"> <%= link_to "FAVORITOS", favorites_path, class: "text-decoration-none text-dark" %> </p>

      </div>
      <div>
      <p class="btn buttons justify-content-center"> <%= link_to "HOME", root_path, class: "text-decoration-none text-dark" %> </p>
      </div>
    </div>
    <div class= "d-flex justify-content-center align-self-start">
    <p class="btn buttons justify-content-center"> ¿Dudas? Contáctanos </p>
  </div>
</div>